<div class="popup_head"><?php echo $this->translate('Forgot Password',__NAMESPACE__); ?></div>
<div class="popup_content">
    <form method="post" action="/<?php echo $this->layout()->language; ?>/user/forgot-password" id="forgot_password" >
        <div class="inp_item" id="email_div" >
            <label for="email"><?php echo $this->translate('E-mail',__NAMESPACE__); ?></label>
            <input type="text" class="use_code_inp" id="email" name="email" />
        </div>

        <div class="btns_div">
            <!--<input type="submit" value="Send email"/>-->
            <a href="javascript:void(0)" onclick="forgotPassword()"  class="login_btn"><?php echo $this->translate('Send email',__NAMESPACE__); ?></a>
            <!--<a href="#" class="fb_join"></a>-->
        </div>

    </form>
</div>