<p>PLEASE NOTE THE FOLLOWING TERMS AND CONDITIONS FOR PURCHASES MADE ONLINE VIA WWW.TATEVER.AM WEBSITE</p>

<p>Under the present Terms and Conditions</p>
<p>"We" and "us" mean “Wings of Tatev”.</p>
<p>"You" means the person who is placing the order.</p>

<p>Online ticket purchases for the “Wings of Tatev” cableway are strictly subject to the following terms and conditions (“Terms"). By purchasing a “Wings of Tatev” cableway ticket, you agree to the present Terms. You also agree to use your ticket in accordance with the present Terms. Please read these Terms carefully before completing your purchase.</p>
<ol>
    <li>Ticket purchases
        <ol>
            <li>Tickets may be purchased through the <a href="http://www.tatever.am">www.tatever.am</a> (“Site”) website by credit or debit card.</li>
            <li>By completing and submitting an online order through the Site, you are making an offer to purchase ticket(s) for the indicated schedule subject to the present Terms, which, if accepted by us, will result in a binding contract.</li>
            <li>Online reservations made via the Site shall be considered completed once we have processed your payment and sent an email to you confirming your booking, which shall constitute an acceptance of your offer.</li>
            <li>We will not be liable if there is a delay, and we will not accept your order if payment is not authorized.</li>
            <li>All prices and fees include any applicable value added tax.</li>
            <li> Tickets are non-refundable. We will not be responsible in the event that you make any error when purchasing your tickets through the Site (including but not limited to selecting the wrong date or time or the wrong number of tickets). Please ensure that your selection is correct before confirming the booking as tickets cannot be exchanged or refunded at a later stage. Lost, stolen or damaged tickets will not be replaced.</li>
        </ol>
    </li>

    <li>Your information
        <ol>
            <li>We believe that ticket purchases through the Site are absolutely secure. We use the latest industry standard encryption technology to ensure the safety of visitors' personal information. All ordering information (including names and credit card details) is encrypted for maximum security. Credit card and billing information cannot be traced throughout the reservation process.</li>
            <li>All information received by us through ticket purchases on the Site shall be gathered in accordance with our Confidentiality Policy.</li>
        </ol>
    </li>
    <li>Other Conditions
        <ol>
            <li>
                We reserve the right to amend the present Terms from time to time. New Terms shall be posted on the Site. If you do not wish to be governed by the revised Terms, do not place any further orders.<br/>
                The present Terms are governed by the laws of the Republic of Armenia, and you and we agree to use the Armenian courts to settle any disputes that may arise.<br/>
                Should any part of the present Terms become invalid, the remainder shall remain legally valid and enforceable.
            </li>
        </ol>
    </li>
</ol>
