<!--<h2>Dear Customer,</h2>-->
<p>Please be informed that, once purchased, tickets cannot be returned.</p>
<p>If you wish to exchange your Wings of Tatev Aerial Tramway ticket for a different date and/or time, you may do so subject to all conditions listed below, as set forth in Article 23 of the Law of the Republic of Armenia "On Consumer Rights Protection":</p>

<strong>For tickets purchased at the ticket-office:</strong>

<ol>
    <li>The ticket has not been used, is legible and intact, and has not been damaged in any way.</li>
    <li>The ticket is submitted for exchange within 14 (fourteen) days from the date of purchase.</li>
    <li>Cash receipt is submitted along with the ticket.</li>
</ol>

<strong>For e-tickets:</strong>
<ol>
    <li>The ticket has not been used.</li>
    <li>The ticket is submitted for exchange within 14 (fourteen) days from the date of purchase.</li>
    <li>The customer can provide the confirmation code, name of the buyer..</li>
</ol>
<p>The date of the new ticket issued to you must be set within 30 (thirty) days following the date of exchange.</p>
