<ul>
    <li>Bring printed ticket with you and insert it in Vario-Gate.</li>
    <li>Open confirmation email with tickets on your smartphone screen, and directly insert in Vario-Gate.</li>
    <li>If you can’t print out bought ticket or forgot to bring it, so you can come to ticket-box office and purchase printed tickets by telling confirmation number with First name and Last. Service price is 100 dram. </li>
</ul>


