
<?php echo $this->message ?>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4" style="float:none; margin: 0 auto;">
        <div class="well no-padding">
            <form action="/forgot-password/<?php echo  $this->token ?>" method="post" id="login-form" class="smart-form client-form" novalidate="novalidate">
                <header>
                    Recover Password
                </header>

                <fieldset>

                    <section>
                        <label class="label">New Password</label>
                        <label class="input"> <i class="icon-append fa fa-user"></i>
                            <input type="password" name="password">
                            <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter username</b></label>
                    </section>
                </fieldset>
                <footer>
                    <button type="submit" class="btn btn-primary">
                        Change
                    </button>
                </footer>
            </form>

        </div>
    </div>
</div>