<?php echo $this->doctype(); ?>
<?php
$children = $this->viewModel()->getCurrent()->getChildren();
$viewModel = $children[0];
$layoutViewModel = $this->viewModel()->getRoot();
$user = $layoutViewModel->headerUser;
?>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <title> Hike Armenia </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Styles -->
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/dataTables.responsive.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/jquery.datatables.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/font-awesome.min.css">

    <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/smartadmin-production-plugins.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/smartadmin-production.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/smartadmin-skins.min.css">


    <!-- SmartAdmin RTL Support  -->
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/smartadmin-rtl.min.css">

    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/admin.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/admin-files/css/chessboard-0.3.0.min.css">
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" type='text/css' href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">


    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="/admin-files/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/admin-files/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/admin-files/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/admin-files/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="/admin-files/img/splash/ipad-landscape.png"
          media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="/admin-files/img/splash/ipad-portrait.png"
          media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="/admin-files/img/splash/iphone.png"
          media="screen and (max-device-width: 320px)">

</head>
<body class=""><!-- HEADER -->
<!-- END HEADER -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->

<!-- END NAVIGATION -->
<!-- MAIN PANEL -->
<div id="content" class="studentPage">
    <?php echo $this->content; ?>
</div>
<!-- END MAIN CONTENT -->

<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<script data-pace-options='{ "restartOnRequestAfter": true }' src="/admin-files/js/plugin/pace/pace.min.js"></script>
<!--[if IE 8]>
<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
<![endif]-->
<?php

echo $this->headScript()

    ->prependFile($this->basePath() . '/admin-files/js/chessboard-0.3.0.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/bootstrap/dataTables.responsive.js')
    ->prependFile($this->basePath() . '/admin-files/js/bootstrap/dataTables.bootstrap.js')
    ->prependFile($this->basePath() . '/admin-files/js/jquery.waypoints.min.js') //viewport trigger lib
    ->prependFile($this->basePath() . '/admin-files/js/plugin/fullcalendar/jquery.fullcalendar.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/masonry/imagesloaded.pkgd.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/chartjs/chart.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/masonry/masonry.pkgd.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/moment/moment.min.js')
    ->prependFile($this->basePath() . '/js/jquery.form.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/datatables/jquery.dataTables.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/ckeditor/ckeditor.js')
    ->prependFile($this->basePath() . '/admin-files/js/app.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/jquery.are-you-sure.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/fastclick/fastclick.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/msie-fix/jquery.mb.browser.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/bootstrap-slider/bootstrap-slider.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/select2/select2.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/masked-input/jquery.maskedinput.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/jquery-validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/sparkline/jquery.sparkline.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/smartwidgets/jarvis.widget.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/notification/SmartNotification.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/bootstrap/bootstrap.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/admin.js')

    ->prependFile($this->basePath() . '/admin-files/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/app.config.js')
    ->prependFile($this->basePath() . '/admin-files/js/libs/jquery-ui-1.10.3.min.js')
    ->prependFile($this->basePath() . '/admin-files/js/libs/jquery-2.1.1.min.js')
?>
<div class="loader"></div>
</body>
</html>
