<div class="row">
    <div class="col-sm-9">
        <h1 class="page-title txt-color-blueDark">
            <a href="/admin">
                <i class="fa-fw fa fa-home"></i>
                Dashboard
            </a>
            <span>> Guide Reviews</span>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="jarviswidget jarviswidget-color-blueDark">
            <header role="heading">

                <span class="widget-icon"> <i class="fa fa-table"></i> </span>

                <h2>Guide Reviews</h2>
            </header>
            <div role="content">
                <div class="widget-body no-padding">
                    <div class="tab-content ">
                        <div id="guideReviewsTable" class="table-responsive tab-pane fade active in">
                            <table class="table table-hover ">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Guide Name</th>
                                    <th>Rating</th>
                                    <th>User Name</th>
                                    <th>Status</th>
                                    <th style="width:190px;">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>