<div class="row">
    <div class="col-sm-9">
        <h1 class="page-title txt-color-blueDark">
            <a href="/admin">
                <i class="fa-fw fa fa-home"></i>
                Dashboard
            </a>
            <span>> Trails</span>
        </h1>
    </div>
    <div class="col-sm-3">
        <a href="<?php echo $this->url("admin", array("action" => "add-trail")); ?>" class="btn btn-info btn-lg">
            <i class="fa fa-plus-circle"></i>
            Add New
        </a>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="jarviswidget jarviswidget-color-blueDark">

                <header role="heading">

                    <span class="widget-icon"> <i class="fa fa-table"></i> </span>

                    <h2>All Trails</h2>
                </header>
                <div role="content">
                    <div class="widget-body no-padding">
                        <div class="tab-content ">
                            <div id="trailsTable" class="table-responsive tab-pane fade active in">
                                <table class="table table-hover ">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Region</th>
                                        <th style="width:70px;">Number of guides</th>
                                        <th style="width:140px;">Number of accommodations</th>
                                        <th>Status</th>
                                        <th style="width:92px;">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>


        </div>
    </div>
</div>