<html>
<head lang="en">
    <meta charset="utf-8">
    <style>
        .stripedTable tr:nth-child(odd) {
            background:#fff;
            margin-left:0;
        }

    </style>
</head>

<body>

<div dir="ltr">

    <table bgcolor="#282e3a" width="100%" border="0" cellspacing="0" cellpadding="0">
        <tbody>
        <tr>
            <td>
                <table width="640" border="0" align="center" cellpadding="0" cellspacing="0">
                    <tbody>

                    <tr>
                        <td width="10" height="17"></td>
                    </tr>
                    <tr>
                        <td>
                            <table width="640" border="0" cellspacing="0" cellpadding="0">
                                <tbody>
                                <tr>
                                    <td width="20" valign="top" height="565"></td>
                                    <td valign="top" bgcolor="#FFFFFF">
                                        <table width="600" border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                            <tr>
                                                <td bgcolor="#f8f8f8">
                                                    <table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
                                                        <tbody>
                                                        <tr>
                                                            <td width="10" height="15"></td>
                                                        </tr>
                                                        <tr>
                                                            <td>
                                                                <table width="550" border="0" align="center" cellpadding="0" cellspacing="0">
                                                                    <tbody>
                                                                    <tr>
                                                                        <td width="42"></td>
                                                                        <td width="10" height="10"></td>
                                                                        <td align="left" style="font-family:Arial,Helvetica,sans-serif;font-size:18px;color:#555555;font-weight:bold">
                                                                            <strong>You have a new mail entry Mirhav website contact form</strong>
                                                                        </td>
                                                                        <td width="174" align="center">
                                                                            <img style="display:block" border="0" src="http://mirhav.bigbek.com/images/logo_footer.png"
                                                                                 width="85" height="65" alt="logo mirhav roadway" title="Logo tatever roadway" class="CToWUd">
                                                                        </td>
                                                                    </tr>
                                                                    </tbody>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td width="10" height="15"></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <table style="border-top:#dddddd solid 1px;border-bottom:#dddddd solid 1px" width="600" border="0" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td bgcolor="#eeeeee">
                                                                <table width="550" border="0" align="center" cellpadding="0" cellspacing="0">
                                                                    <tbody>

                                                                    <tr>
                                                                        <td>
                                                                            <table width="600" border="0" cellspacing="0" cellpadding="0">
                                                                                <tbody class="stripedTable">
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Name
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->name; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Surname
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->surname; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Email
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->email; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Phone
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->phone; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Arrive
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->arrive; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Depart
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->depart; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Adults
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->adults; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Children
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->children; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Room type:
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->roomType; ?>
                                                                                    </td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        Comments:
                                                                                    </td>
                                                                                    <td width="70" align="left" valign="top" style="padding:15px;padding-left: 65px;font-family:Tahoma,Geneva,sans-serif;font-size:13px;color:#666666;font-weight:bold; ">
                                                                                        <?php echo $this->comments; ?>
                                                                                    </td>
                                                                                </tr>

                                                                                </tbody>
                                                                            </table>
                                                                        </td>
                                                                    </tr>

                                                                    </tbody>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td bgcolor="#FFFFFF">
                                                                <table width="550" border="0" align="center" cellpadding="0" cellspacing="0">
                                                                    <tbody>
                                                                    <tr>
                                                                        <td>
                                                                            <table width="550" border="0" cellspacing="0" cellpadding="0">
                                                                                <tbody>
                                                                                <tr>
                                                                                    <td width="10" height="20"></td>
                                                                                </tr>
                                                                                <tr>
                                                                                    <td>

                                                                                </tr>
                                                                                <tr>
                                                                                    <td style="border-bottom:1px solid #dddddd" width="10" height="20"></td>
                                                                                </tr>
                                                                                </tbody>
                                                                            </table>
                                                                        </td>
                                                                    </tr>
                                                                    </tbody>
                                                                </table>
                                                            </td>
                                                        </tr>

                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>

                                            <tr>
                                                <td bgcolor="#ce142b"></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                    <td width="20" height="565" valign="bottom"></td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td width="640" height="20"></td>
                    </tr>
                    <tr>
                        <td width="10" height="10"></td>
                    </tr>
                    <tr>
                        <td align="center" bgcolor="#ffffff" style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#465167"> </td>
                    </tr>
                    <tr> </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>

    <div class="yj6qo"></div>
    <div class="adL">
    </div>
</div>
<div class="adL">
</div>

</body>
</html>