<table  style="width: 740px; height: 181px; border:30px solid transparent; color: black">
    <tbody>
    <tr>
        <td style="width: 118px;" valign="top"><img src="http://<?php echo $_SERVER['HTTP_HOST']?>/img/logo.png" alt="" style="width: 100px;" /></td>
        <td valign="top" style="width: 550px;">
            <h2 style='margin:0'>Hi <?php echo $this->userFirstName ?></h2>
            <p>To reset your password on the HIKEArmenia app, please press <a href="<?php echo' http://'.$_SERVER['SERVER_NAME'].'/forgot-password/'.$this->token ?>">here</a>.</p>
            <p>If you didn't make that request, kindly ignore this message.</p>
            <p>Best,</p>
                <p>HIKEArmenia</p>
        </td>
    </tr>
    </tbody>
</table>