
<table style="width: 740px; height: 181px; border:30px solid transparent">
    <tbody>
    <tr>
        <td style="width: 118px;" valign="top"><img src="http://<?php echo $_SERVER['HTTP_HOST']?>/img/logo.png" alt="" style="width: 100px;" /></td>
        <td valign="top" style="width: 550px;">
            <h2 style='margin:0'>Hi <?php echo $this->userFirstName ?></h2>
            <p>Welcome to HIKEArmenia, and thank you for joining the adventure!</p>
            <p>If you have questions or comments, please send feedback our way at <a href="mailto:contact@hikearmenia.com">contact@hikearmenia.com</a>!</p>
            <p>Wanna know more about us? Read more about how the app came to life here, and about our trailblazing trips around Armenia here (<a href="https://onearmenia.org/campaign/hikearmenia-2/">https://onearmenia.org/campaign/hikearmenia-2/)</a> <a href="https://onearmenia.org/blog_post/hikearmenia-update-armenias-mountains-await-you/">(https://onearmenia.org/blog_post/hikearmenia-update-armenias-mountains-await-you/)</a>.</p>
            <p>We look forward to seeing you on the trails!
            </p>
        </td>
    </tr>
    </tbody>
</table>